// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxkpvyvqoebrzifiumpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4a3B2eXZxb2VicnppZml1bXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3Njk3MTgsImV4cCI6MjA2ODM0NTcxOH0.1N7tuOq6INH5eM3ID7lPJRnr08JFU0FduTC8hWIB8aE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});